Repository zebrunner/carina, pull requests merged in 2020-09, with the labels that each got.

#1090 #1089: simplified refindElement code block
  carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
Labels: build-snapshot

#1099 catch any exception during server log reading
  carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
Labels: build-snapshot

#1105 [#544] deleted IJiraUpdater interface and all occurrences and related properties and dependencies
  archetype/src/main/resources/archetype-resources/src/main/resources/_config.properties
  carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
  carina-core/src/main/resources/config.properties
  carina-utils/pom.xml
  carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/jira/DefaultJiraUpdater.java
  carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/jira/IJiraUpdater.java
  carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/jira/Jira.java
  carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
  carina-utils/src/test/resources/config.properties
  docs/configuration.md
Labels: enhancement

#1106 [#1021] hub_mode property was replaced with capabilities.provider and HubType enum was deleted
  carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
  carina-core/src/main/resources/config.properties
  carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
  carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/AbstractFactory.java
  carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/DriverFactory.java
  carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
  carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
Labels: enhancement

#1107 [#1082] enable_headless_mode property added for headless browsers testing
  carina-core/src/main/resources/config.properties
  carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
  carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
  docs/configuration.md
Labels: enhancement

#1112 #1111: added disabling of enableVNC and Video caps in case of headless mode. Added more logs.
  carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
Labels: build-snapshot, enhancement

#1109 #1078: made ability to use custom retry analyzer
  carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
Labels: bug, build-snapshot

#1120 #1119: return default max_log_file_size=150 in resolver
  archetype/src/main/resources/archetype-resources/src/main/resources/_config.properties
  carina-api/src/test/resources/config.properties
  carina-aws-s3/src/test/resources/config.properties
  carina-core/src/main/resources/config.properties
  carina-proxy/src/test/resources/config.properties
  carina-reporting/src/test/resources/config.properties
  carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/log/ThreadLogAppender.java
  carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
  carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/PlaceholderResolver.java
  carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/R.java
  carina-utils/src/test/resources/_config.properties
  carina-utils/src/test/resources/config.properties
  carina-webdriver/src/test/resources/config.properties
  docs/configuration.md
Labels: build-snapshot
